using System.Collections.Generic;

namespace WarOfRightsWeb.Constants
{
    // NOTE: Generated by WarOfRightsTools from text_ui_ingame.xml

    public static class Maps
    {
        public const string EmptySkirmishMapImagePath = "maps\\Empty_skirmish.png";

        // NOTE: Database map identifiers
        public const string HookersPush = "HookersPush";
        public const string HagerstownTurnpike = "HagerstownTurnpike";
        public const string MillersCornfield = "MillersCornfield";
        public const string EastWoods = "EastWoods";
        public const string EastWoodsSkirmish = "EastWoodsSkirmish";
        public const string BloodyLane = "BloodyLane";
        public const string PryFord = "PryFord";
        public const string PryGristMill = "PryGristMill";
        public const string PryHouse = "PryHouse";
        public const string WestWoods = "WestWoods";
        public const string DunkerChurch = "DunkerChurch";
        public const string BurnsideBridge = "BurnsideBridge";
        public const string OttoSherrickFarm = "OttoSherrickFarm";
        public const string PiperFarm = "PiperFarm";
        public const string NicodemusHill = "NicodemusHill";
        public const string CookesCountercharge = "CookesCountercharge";
        public const string RouletteLane = "RouletteLane";
        public const string HillsCounterattack = "HillsCounterattack";
        public const string MarylandHeights = "MarylandHeights";
        public const string RiverCrossing = "RiverCrossing";
        public const string Downtown = "Downtown";
        public const string HighStreet = "HighStreet";
        public const string ShenandoahStreet = "ShenandoahStreet";
        public const string HarpersGraveyard = "HarpersGraveyard";
        public const string WashingtonStreet = "WashingtonStreet";
        public const string SchoolHouseRidge = "SchoolHouseRidge";
        public const string BolivarHeightsCamp = "BolivarHeightsCamp";
        public const string BolivarHeightsRedoubt = "BolivarHeightsRedoubt";
        public const string GarlandsStand = "GarlandsStand";
        public const string HatchsAttack = "HatchsAttack";
        public const string ColquittsDefence = "ColquittsDefence";
        public const string RenosFall = "RenosFall";
        public const string CoxsPush = "CoxsPush";
        public const string AndersonsCounterattack = "AndersonsCounterattack";
        public const string PicketPatrol = "PicketPatrol";
        public const string HarpersFerryUSA = "HarpersFerryUSA";
        public const string DrillCampUSA = "DrillCampUSA";
        public const string DrillCampCSA = "DrillCampCSA";

        public static string[] AntietamMaps =
        {
            EastWoodsSkirmish,
            HookersPush,
            HagerstownTurnpike,
            MillersCornfield,
            EastWoods,
            NicodemusHill,
            BloodyLane,
            PryFord,
            PryGristMill,
            PryHouse,
            WestWoods,
            DunkerChurch,
            BurnsideBridge,
            CookesCountercharge,
            OttoSherrickFarm,
            RouletteLane,
            PiperFarm,
            HillsCounterattack,
        };

        public static string[] HarpersFerryMaps =
        {
            MarylandHeights,
            RiverCrossing,
            Downtown,
            SchoolHouseRidge,
            HighStreet,
            BolivarHeightsCamp,
            ShenandoahStreet,
            HarpersGraveyard,
            BolivarHeightsRedoubt,
            WashingtonStreet,
        };

        public static string[] SouthMountainMaps =
        {
            GarlandsStand,
            CoxsPush,
            HatchsAttack,
            AndersonsCounterattack,
            RenosFall,
            ColquittsDefence,
        };

        public static string[] DrillCampMaps =
        {
            DrillCampCSA, 
            DrillCampUSA, 
            HarpersFerryUSA
        };
    }
}
