using System.Collections.Generic;

namespace WarOfRightsWeb.Constants
{
    // NOTE: Generated by WarOfRightsTools from text_ui_ingame.xml

    public static class Maps
    {
        // NOTE: Generated item identifiers 
        // TODO: Refactor constant names
        public const string HookersPush = "HookersPush";
        public const string HagerstownTurnpike = "HagerstownTurnpike";
        public const string MillersCornfield = "MillersCornfield";
        public const string EastWoods = "EastWoods";
        public const string EastWoodsSkirmish = "EastWoodsSkirmish";
        public const string BloodyLane = "BloodyLane";
        public const string PryFord = "PryFord";
        public const string PryGristMill = "PryGristMill";
        public const string PryHouse = "PryHouse";
        public const string WestWoods = "WestWoods";
        public const string DunkerChurch = "DunkerChurch";
        public const string BurnsideBridge = "BurnsideBridge";
        public const string OttoSherrickFarm = "OttoSherrickFarm";
        public const string PiperFarm = "PiperFarm";
        public const string NicodemusHill = "NicodemusHill";
        public const string CookesCountercharge = "CookesCountercharge";
        public const string RouletteLane = "RouletteLane";
        public const string HillsCounterattack = "HillsCounterattack";
        public const string MarylandHeights = "MarylandHeights";
        public const string RiverCrossing = "RiverCrossing";
        public const string Downtown = "Downtown";
        public const string HighStreet = "HighStreet";
        public const string ShenandoahStreet = "ShenandoahStreet";
        public const string HarpersGraveyard = "HarpersGraveyard";
        public const string WashingtonStreet = "WashingtonStreet";
        public const string SchoolHouseRidge = "SchoolHouseRidge";
        public const string BolivarHeightsCamp = "BolivarHeightsCamp";
        public const string BolivarHeightsRedoubt = "BolivarHeightsRedoubt";
        public const string GarlandsStand = "GarlandsStand";
        public const string HatchsAttack = "HatchsAttack";
        public const string ColquittsDefence = "ColquittsDefence";
        public const string RenosFall = "RenosFall";
        public const string CoxsPush = "CoxsPush";
        public const string AndersonsCounterattack = "AndersonsCounterattack";
        public const string PicketPatrol = "PicketPatrol";
        public const string HarpersFerryUSA = "HarpersFerryUSA";
        public const string DrillCampUSA = "DrillCampUSA";
        public const string DrillCampCSA = "DrillCampCSA";

        // NOTE: Generated display names
        public static Dictionary<string, string> DisplayNames = new()
        {
            { HookersPush, "Hooker's Push" },
            { HagerstownTurnpike, "Hagerstown Turnpike" },
            { MillersCornfield, "Miller's Cornfield" },
            { EastWoods, "East Woods" },
            { EastWoodsSkirmish, "East Woods Skirmish" },
            { BloodyLane, "Bloody Lane" },
            { PryFord, "Pry Ford" },
            { PryGristMill, "Pry Grist Mill" },
            { PryHouse, "Pry House" },
            { WestWoods, "West Woods" },
            { DunkerChurch, "Dunker Church" },
            { BurnsideBridge, "Burnside Bridge" },
            { OttoSherrickFarm, "Otto & Sherrick Farm" },
            { PiperFarm, "Piper Farm" },
            { NicodemusHill, "Nicodemus Hill" },
            { CookesCountercharge, "Cooke's Countercharge" },
            { RouletteLane, "Roulette Lane" },
            { HillsCounterattack, "Hill's Counterattack" },
            { MarylandHeights, "Maryland Heights" },
            { RiverCrossing, "River Crossing" },
            { Downtown, "Downtown" },
            { HighStreet, "High Street" },
            { ShenandoahStreet, "Shenandoah Street" },
            { HarpersGraveyard, "Harpers Graveyard" },
            { WashingtonStreet, "Washington Street" },
            { SchoolHouseRidge, "School House Ridge" },
            { BolivarHeightsCamp, "Bolivar Heights Camp" },
            { BolivarHeightsRedoubt, "Bolivar Heights Redoubt" },
            { GarlandsStand, "Garland's Stand" },
            { HatchsAttack, "Hatch's Attack" },
            { ColquittsDefence, "Colquitt's Defence" },
            { RenosFall, "Reno's Fall" },
            { CoxsPush, "Cox's Push" },
            { AndersonsCounterattack, "Anderson's Counterattack" },
            { PicketPatrol, "Picket Patrol" },
            { HarpersFerryUSA, "Harpers Ferry USA" },
            { DrillCampUSA, "Drill Camp USA" },
            { DrillCampCSA, "Drill Camp CSA" },
        };

        // SkirmishInfo(?<id>.+)DateTime
        // NOTE: Generated battle dates and time
        public static Dictionary<string, string> DateTimes = new()
        {
            { HookersPush, "September 17th - 06:00" },
            { HagerstownTurnpike, "September 17th - 06:30" },
            { MillersCornfield, "September 17th - 07:00" },
            { EastWoods, "September 17th - 07:20" },
            { EastWoodsSkirmish, "September 16th - 20:00" },
            { BloodyLane, "September 17th - 09:00" },
            { PryFord, "September 17th - 09:30" },
            { PryGristMill, "September 17th - 10:00" },
            { PryHouse, "September 17th - 10:00" },
            { WestWoods, "September 17th - 10:00" },
            { DunkerChurch, "September 17th - 10:30" },
            { BurnsideBridge, "September 17th - 11:30" },
            { OttoSherrickFarm, "September 17th - 12:30" },
            { PiperFarm, "September 17th - 16:30" },
            { NicodemusHill, "September 17th - 08:45" },
            { CookesCountercharge, "September 17th - 12:00" },
            { RouletteLane, "September 17th - 12:45" },
            { HillsCounterattack, "September 17th - 17:00" },
            { MarylandHeights, "September 13th - 09:30" },
            { RiverCrossing, "September 15th - 09:30" },
            { Downtown, "September 15th - 10:00" },
            { HighStreet, "September 15th - 11:00" },
            { ShenandoahStreet, "September 15th - 13:30" },
            { HarpersGraveyard, "September 15th - 14:30" },
            { WashingtonStreet, "September 15th - 15:30" },
            { SchoolHouseRidge, "September 15th - 06:30" },
            { BolivarHeightsCamp, "September 15th - 09:00" },
            { BolivarHeightsRedoubt, "September 15th - 10:00" },
            { GarlandsStand, "September 14th - 10:00 close to Fox's Gap" },
            { HatchsAttack, "September 14th - 18:30 close to Turner's Gap" },
            { ColquittsDefence, "September 14th - 19:00 Turner's Gap" },
            { RenosFall, "September 14th - 18:00 close to Fox's Gap" },
            { CoxsPush, "September 14th - 11:00 Fox's Gap" },
            { AndersonsCounterattack, "September 14th - 18:00 Fox's Gap" },
            { PicketPatrol, "September, 1862" },
            { HarpersFerryUSA, "September, 1862" },
            { DrillCampUSA, "September, 1862" },
            { DrillCampCSA, "September, 1862" },
        };

        // SkirmishInfo(?<id>.+)Description
        // NOTE: Generated item descriptions (prepared for html)
        public static Dictionary<string, string> Descriptions = new()
        {
            { HookersPush, "In the early fog of dawn, Union General Joseph Hooker pushes southwards with his I Corps, starting from the edge of North Woods, past the R. Miller Farm and through the Miller Cornfield only to be engaged south of it by defending Confederate General Ewell's Division at about 7 AM." },
            { HagerstownTurnpike, "Upon leaving Miller’s Cornfield, the Union attacks the Confederates who are defending the Hagerstown Turnpike, a road running next to the cornfield. Its fenced in sides and the road itself functions as a clear line between Jackson’s forces in the West Woods and Hooker’s south of the cornfield." },
            { MillersCornfield, "An hour after the early morning actions of General Hooker and his Corps near the Miller farmstead, the damaged cornfield is subjected to a new infusion of blood, this time from the men of Hood's division. A withering fire from several sides mean that terrible casualties are wrought." },
            { EastWoods, "As Confederate General Hood attempts to push the advancing Union General Hooker’s I Corps back into the Cornfield, some of his forces also push against the Union holding in the East Woods directly adjacent to Miller’s Cornfield.  " },
            { EastWoodsSkirmish, "During the late afternoon of September 16th, General Hooker takes his Corps across Antietam creek at the upper bridge in order to locate the rebel flank. In the waning light, the 42nd PA and 3rd PA reserves are sent out in a skirmish formation to probe the East Woods for rebels." },
            { BloodyLane, "A sunken road often used by farmers becomes a natural fort against a Union onslaught of Rebel lines as Union General French pushes forward with his 3rd Division and becomes engaged with elements of Confederate General D.H. Hill’s Division entrenched in the road." },
            { PryFord, "In this alternate scenario, grey-clad soldiers hold an important point near a ford on the Antietam Creek, and are attacked by dismounted Union cavalry under Pleasanton used by Union Commander General McClellan as skirmishers probing for the enemy throughout the day of fighting." },
            { PryGristMill, "In this alternate scenario, Hooker's forces must contend with Confederate skirmishers holding an important crossing point of the Little Antietam creek. Pry’s Grist Mill is situated near the confluence of Little Antietam and Antietam Creek and is a major supplier of flour in the region. " },
            { PryHouse, "In this alternative scenario pockets of Confederate forces have managed to sneak by the Union line and are attacking Pry House, headquarter of commanding Union General George B. McClellan. " },
            { WestWoods, "General Edwin Sumner's Union Second Corps advances into the West Woods where they are met by Confederate Wing Commander Jackson’s men. Union General John Sedgwick's division is performing a series of reckless charges into the Confederates at very high costs to break the Confederate line." },
            { DunkerChurch, "Union General Greene pushes his Division towards the rebel-held whitewashed church on the outskirts of the West Woods from the direction of the burning Mumma Farm. The church is a focal point of several Union attacks as it sits elevated on a small plateau. " },
            { BurnsideBridge, "After several hours of preparation, Union General Burnside is ready to advance the IX Corps against Confederate General Toombs’ Brigade of skirmishers whom, while being vastly outnumbered, holds the heights overlooking the Lower Bridge crossing Antietam Creek." },
            { OttoSherrickFarm, "The idyllic farms of the Otto and Sherrick families becomes a heavily contested area as the two forces clash. The farms are situated in close proximity to the Lower Bridge and moving towards the town of Sharpsburg dictates passing their grounds." },
            { PiperFarm, "The 7th Maine is ordered by Colonel Irwin to push past the bodies at the Bloody Lane, the Piper Cornfield, the apple orchard and attack the Piper farm buildings themselves, which act as headquarters for Confederate Wing Commander General Longstreet. 4 Confederate brigades await them." },
            { NicodemusHill, "Confederates are defending Jackson's artillery positioned on Nicodemus Hill from the Union attacking from the direction of Miller farm. The commanding viewpoint offered by Nicodemus Hill offers Washington’s, Chew’s, and Pelham’s batteries devastating fire down the Union lines." },
            { CookesCountercharge, "After several hours with no reinforcements, Union General Greene is forced to withdraw from his salient in the West Woods. Confederate Colonel Cooke orders a countercharge towards Mumma Farm in response to the fleeing Federals." },
            { RouletteLane, "The 3rd Arkansas and 27th North Carolina under Colonel Cooke find themselves on the flank of the Federals now in possession of the Sunken Road. The 1st Delaware and 14th Indiana are tasked with holding the rebels back at Roulette Lane." },
            { HillsCounterattack, "Confederate General Hill arrives from Harper's Ferry late in the day with his Light Division partially wearing captured Federal uniforms. The Division smashes into the flank of the advancing Burnside's Corps which has been delayed heavily earlier in the day at the Lower Bridge." },
            { MarylandHeights, "Early on the morning of the 13th, Kershaw’s and Barksdale’s Brigades of Confederates attack the Maryland Heights while the 32nd Ohio and 126th New York try to guard the approach to Harper’s Ferry." },
            { RiverCrossing, "In this fictitious scenario, Confederates under General McLaws desperately attempt to cross the Potomac River to assault the town of Harper’s Ferry from both sides." },
            { Downtown, "In this fictitious scenario, the Confederates have breached Camp Hill, and are now assaulting the downtown area of Harper’s Ferry where the last defenders doggedly try to hold out against them." },
            { HighStreet, "In this fictitious scenario, the Union garrison under General Miles attempt to defend the north side of Camp Hill against Confederate assaults after their taking of the Bolivar Heights. " },
            { ShenandoahStreet, "In this semi-fictitious scenario, AP Hill has broken past the southern defenses of Bolivar Heights, and is now threatening to take the downtown region of Harper’s Ferry as blue-clad defenders scramble to stop the Confederates." },
            { HarpersGraveyard, "In this fictitious scenario, following the taking of Bolivar Heights, the Confederates are launching an assault on the last holdouts of the garrison via the historic Harper’s Graveyard." },
            { WashingtonStreet, "In this fictitious scenario, the Union garrison attempt to defend against Confederates now streaming down Camp Hill by way of the main thoroughfare to Harper’s Ferry from Bolivar – Washington Street." },
            { SchoolHouseRidge, "During the siege of Harper's Ferry, General Stonewall Jackson had lined a large portion of his force along Schoolhouse Ridge, which sat opposite a valley overlooked by the Bolivar Heights, which the Union had hastily fortified. In this fictitious scenario, the Confederates attempt to make a frontal charge against the strong defenses of the Union!" },
            { BolivarHeightsCamp, "The Bolivar Heights was an important and strategic position for Union forces during their garrison of the town, the ridge also serving as a partial campsite to the 15,000 stationed in the beautiful valley. In this fictitious scenario, Confederate forces have breached the hastily-made defences, while Union forces desperately try to muster a counterattack." },
            { BolivarHeightsRedoubt, "The Bolivar Heights was an important and strategic position for Union forces during their garrison of the town, the ridge also serving as a partial campsite to the 15,000 stationed in the beautiful valley. In this fictitious scenario, Confederate forces are attacking the artillery redoubt of the entrenched Union forces." },
            { GarlandsStand, "CSA Brig. General Samuel Garland having been ordered by Maj. Gen. D.H. Hill to defend Fox's Gap and its road - directly exposing the wagon trains of the Confederate army should it fall, is now deploying his brigade next to the Wise Farm. To his immediate front Union Colonel Scammon's brigade consisting of the 30th and 12th Ohio is advancing and engaging with the 13th and 20th North Carolina while the 23rd Ohio is putting pressure on his far too drawn-out line's right flank." },
            { HatchsAttack, "In an effort to secure the southern part of South Mountain itself and thus open up the flank of Confederate Major General D.H. Hill situated at the strong defensive positions at Mountain House and on the Dahlgren Road at Turner's Gap, Union Brig. Gen. John Hatch's 3500-man division pushes onwards and upwards through some of the most difficult and rocky terrain of the battlefield. On top of the crest CSA General Garnett's 400-man division is rushing forwards to safeguard the flank of the mountain gap." },
            { ColquittsDefence, "Positioned behind a stonewall at the base of Turner's Gap and on the fenced-in Dahlgren Road running above the gap, overlooking the National Road headed into Turner's Gap, CSA Colonel Colquitt's brigade readies itself for the attack it knows is coming after having witnessed Union Gen. Hatch's attack on Garnett to the left of Colquitt's brigade an hour earlier. On the National Road in front of them, Union Gen. Gibbon's brigade begins its slow but steady push with an iron-like determination." },
            { RenosFall, "After the Confederate collapse at Fox's Gap earlier in the day due to the attacks by Union Maj. Gen. Reno's IX Corps, CSA Brig. Gen. Hood now orders his division south to relieve the battered Confederate lines in an effort to regain a foothold at the gap. To deny the Confederates the chance of doing so, the 51st New York and Pennsylvania are sent forward with the Corps commander in close proximity in order to inspire his troops and inspect the lines." },
            { CoxsPush, "As the 30th and 12th Ohio attack the left flank of Garland's Brigade, Union Division Commander Jacob Cox pushes forward the 36th and 23rd Ohio to engage the Confederate 5th North Carolina as well as the 23rd North Carolina, having just reinforced the stretched out and besieged Confederate line. Between the two lines is Fox's Gap, a windswept, valley-like gap covered in stonewalls, fencing in the numerous fields covering the area." },
            { AndersonsCounterattack, "With but a few hours of daylight left the 9th and 89th New York along with Clark's Battery take up a defensive position on the northern side of Fox's Gap, defended by Garland's, now broken, Brigade earlier in the day. CSA Gen. G.B. Anderson, arriving with badly needed reinforcements to the remnants of the Confederate force, targets Clark's Battery and the two New York regiments for his counterattack. " },
            { PicketPatrol, "Eliminate enemy picket force.<br>One life per round.<br>Random team spawn points.<br>Strict formation rules." },
            { HarpersFerryUSA, "Situated in the beautiful Shenandoah Valley, Bolivar Heights is one of three the commands an overlook of the town of Harper's Ferry below. Camp Hill and the Bolivar Heights were taken over by those garrisoning this strategically important confluence of rail and water." },
            { DrillCampUSA, "Nestled in the lush and gently rolling hills of central Maryland, a regiment-sized camp has been set up among various farmsteads in 1862. " },
            { DrillCampCSA, "Having crossed the Potomac earlier in the week, Confederate forces have carved out space among the ample farmland of central Maryland for a regiment-sized encampment during the Maryland Campaign of 1862. " },
        };
    }
}
