using System.Collections.Generic;

namespace WarOfRightsWeb.Constants
{
    public static class RegimentsInfo
    {
        // NOTE: Generated by WarOfRightsTools from all regimental json files       

        public static Dictionary<string, Dictionary<string, int>> WeaponsPool = new()
        {
            {
                Regiments.Alabama13th,
                new()
                {
                    { Weapons.SpringfieldM1855, 30 },
                    { Weapons.PatternEnfield1853, 70 }
                }
            },
            {
                Regiments.Alabama3rd,
                new()
                {
                    { Weapons.Mississippi1841, 100 }
                }
            },
            {
                Regiments.Alabama4th,
                new()
                {
                    { Weapons.SpringfieldM1855, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.AlabamaBtl5th,
                new()
                {
                    { Weapons.Mississippi1841, 70 },
                    { Weapons.Whitworth, 30 }
                }
            },
            {
                Regiments.Alabama6th,
                new()
                {
                    { Weapons.LorenzM1854, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.Alabama8th,
                new()
                {
                    { Weapons.SpringfieldM1855, 30 },
                    { Weapons.PatternEnfield1853, 70 }
                }
            },
            {
                Regiments.Arkansas3rd,
                new()
                {
                    { Weapons.PatternEnfield1853, 70 },
                    { Weapons.SpringfieldM1842, 30 }
                }
            },
            {
                Regiments.BatteryBalthis,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryBlackshear,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryBondurant,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryBoyce,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryBraxton,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryBrockenbrough,
                new()
                {
                    { Weapons.Artillery10PdrParrott, 3 },
                    { Weapons.Artillery12PdrNapoleon, 3 },
                }
            },
            {
                Regiments.BatteryBrooks,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryBrown,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryCarlton,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryCarpenter,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryCourtney,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryDAquin,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryFrench,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryJordan,
                new()
                {
                    { Weapons.Artillery12PdrNapoleon, 1 },
                    { Weapons.Artillery3InchOrdnance, 1 }
                }
            },
            {
                Regiments.BatteryLane,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryManly,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryMaurin,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryMiller,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryPelham,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryPoague,
                new()
                {
                    { Weapons.Artillery3InchOrdnance, 1 },
                    { Weapons.Artillery12PdrNapoleon, 2 },
                }
            },
            {
                Regiments.BatteryRead,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryReily,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryRichardson,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatterySquires,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryWooding,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.Florida8th,
                new()
                {
                    { Weapons.SpringfieldM1842, 30 },
                    { Weapons.SpringfieldM1855, 35 },
                    { Weapons.PatternEnfield1853, 35 }
                }
            },
            {
                Regiments.Georgia13th,
                new()
                {
                    { Weapons.SpringfieldM1855, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.Georgia18th,
                new()
                {
                    { Weapons.SpringfieldM1855, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.Georgia1st,
                new()
                {
                    { Weapons.PatternEnfield1853, 70 },
                    { Weapons.SpringfieldM1842, 30 }
                }
            },
            {
                Regiments.Georgia20th,
                new()
                {
                    { Weapons.Mississippi1841, 70 },
                    { Weapons.PatternEnfield1853, 30 }
                }
            },
            {
                Regiments.Georgia2nd,
                new()
                {
                    { Weapons.SpringfieldM1842, 30 },
                    { Weapons.LorenzM1854, 70 }
                }
            },
            {
                Regiments.Georgia6th,
                new()
                {
                    { Weapons.SpringfieldM1855, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.LouisianaZouaves1st,
                new()
                {
                    { Weapons.Mississippi1841, 70 },
                    { Weapons.SpringfieldM1842, 30 }
                }
            },
            {
                Regiments.Louisiana6th,
                new()
                {
                    { Weapons.SpringfieldM1855, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.Louisiana9th,
                new()
                {
                    { Weapons.SpringfieldM1855, 50 },
                    { Weapons.SpringfieldM1842, 50 }
                }
            },
            {
                Regiments.Mississippi18th,
                new()
                {
                    { Weapons.PatternEnfield1853, 30 },
                    { Weapons.SpringfieldM1855, 30 },
                    { Weapons.SpringfieldM1842, 40 }
                }
            },
            {
                Regiments.Mississippi2nd,
                new()
                {
                    { Weapons.SpringfieldM1842, 70 },
                    { Weapons.PatternEnfield1853, 30 }
                }
            },
            {
                Regiments.NorthCarolina13th,
                new()
                {
                    { Weapons.SpringfieldM1842, 30 },
                    { Weapons.SpringfieldM1855, 35 },
                    { Weapons.PatternEnfield1853, 35 }
                }
            },
            {
                Regiments.NorthCarolina14th,
                new()
                {
                    { Weapons.SpringfieldM1842, 30 },
                    { Weapons.SpringfieldM1855, 35 },
                    { Weapons.PatternEnfield1853, 35 }
                }
            },
            {
                Regiments.NorthCarolina18th,
                new()
                {
                    { Weapons.SpringfieldM1842, 30 },
                    { Weapons.SpringfieldM1855, 35 },
                    { Weapons.PatternEnfield1853, 35 }
                }
            },
            {
                Regiments.NCSharpshooters1st,
                new()
                {
                    { Weapons.SpringfieldM1855, 40 },
                    { Weapons.PatternEnfield1853, 40 },
                    { Weapons.Whitworth, 20 }
                }
            },
            {
                Regiments.NorthCarolina20th,
                new()
                {
                    { Weapons.SpringfieldM1842, 30 },
                    { Weapons.SpringfieldM1855, 35 },
                    { Weapons.PatternEnfield1853, 35 }
                }
            },
            {
                Regiments.NorthCarolina23rd,
                new()
                {
                    { Weapons.SpringfieldM1842, 70 },
                    { Weapons.SpringfieldM1855, 15 },
                    { Weapons.PatternEnfield1853, 15 }
                }
            },
            {
                Regiments.NorthCarolina27th,
                new()
                {
                    { Weapons.SpringfieldM1842, 30 },
                    { Weapons.SpringfieldM1855, 35 },
                    { Weapons.PatternEnfield1853, 35 }
                }
            },
            {
                Regiments.NorthCarolina2nd,
                new()
                {
                    { Weapons.SpringfieldM1842, 20 },
                    { Weapons.SpringfieldM1855, 40 },
                    { Weapons.PatternEnfield1853, 40 }
                }
            },
            {
                Regiments.NorthCarolina4th,
                new()
                {
                    { Weapons.SpringfieldM1842, 20 },
                    { Weapons.SpringfieldM1855, 40 },
                    { Weapons.PatternEnfield1853, 40 }
                }
            },
            {
                Regiments.NorthCarolina5th,
                new()
                {
                    { Weapons.SpringfieldM1861, 80 },
                    { Weapons.PatternEnfield1853, 20 }
                }
            },
            {
                Regiments.SouthCarolina12th,
                new()
                {
                    { Weapons.SpringfieldM1861, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.SouthCarolina17th,
                new()
                {
                    { Weapons.SpringfieldM1861, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.SouthCarolina2nd,
                new()
                {
                    { Weapons.SpringfieldM1861, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.SouthCarolina3rd,
                new()
                {
                    { Weapons.SpringfieldM1861, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.HamptonLegion,
                new()
                {
                    { Weapons.SpringfieldM1861, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.HolcombeLegion,
                new()
                {
                    { Weapons.SharpsCarbine, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.PalmettoSharpshooters,
                new()
                {
                    { Weapons.Mississippi1841, 40 },
                    { Weapons.PatternEnfield1853, 10 },
                    { Weapons.Whitworth, 50 }
                }
            },
            {
                Regiments.Tennessee14th,
                new()
                {
                    { Weapons.PatternEnfield1853, 50 },
                    { Weapons.SpringfieldM1855, 40 },
                    { Weapons.SpringfieldM1842, 10 }
                }
            },
            {
                Regiments.Texas1st,
                new()
                {
                    { Weapons.SpringfieldM1842, 30 },
                    { Weapons.PatternEnfield1853, 40 },
                    { Weapons.SpringfieldM1855, 30 }
                }
            },
            {
                Regiments.Texas4th,
                new()
                {
                    { Weapons.SpringfieldM1842, 20 },
                    { Weapons.PatternEnfield1853, 40 },
                    { Weapons.SpringfieldM1855, 40 }
                }
            },
            {
                Regiments.Texas5th,
                new()
                {
                    { Weapons.SpringfieldM1842, 20 },
                    { Weapons.PatternEnfield1853, 40 },
                    { Weapons.SpringfieldM1855, 40 }
                }
            },
            {
                Regiments.Virginia13th,
                new()
                {
                    { Weapons.PatternEnfield1853, 50 },
                    { Weapons.SpringfieldM1855, 40 },
                    { Weapons.SpringfieldM1842, 10 }
                }
            },
            {
                Regiments.Virginia18th,
                new()
                {
                    { Weapons.PatternEnfield1853, 50 },
                    { Weapons.SpringfieldM1855, 40 },
                    { Weapons.SpringfieldM1842, 10 }
                }
            },
            {
                Regiments.VirginiaBtl1st,
                new()
                {
                    { Weapons.SpringfieldM1861, 40 },
                    { Weapons.PatternEnfield1853, 60 }
                }
            },
            {
                Regiments.VirginiaCavalry1st,
                new()
                {
                    { Weapons.SharpsCarbine, 100 }
                }
            },
            {
                Regiments.VirginiaBtl22nd,
                new()
                {
                    { Weapons.LorenzM1854, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.Virginia30th,
                new()
                {
                    { Weapons.PatternEnfield1853, 50 },
                    { Weapons.SpringfieldM1855, 40 },
                    { Weapons.SpringfieldM1842, 10 }
                }
            },
            {
                Regiments.Virginia33rd,
                new()
                {
                    { Weapons.LorenzM1854, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.Virginia56th,
                new()
                {
                    { Weapons.PatternEnfield1853, 60 },
                    { Weapons.SpringfieldM1855, 30 },
                    { Weapons.SpringfieldM1842, 10 }
                }
            },
            {
                Regiments.Virginia5th,
                new()
                {
                    { Weapons.PatternEnfield1853, 50 },
                    { Weapons.SpringfieldM1855, 10 },
                    { Weapons.SpringfieldM1842, 40 }
                }
            },
            {
                Regiments.BatteryCampbell,
                new()
                {
                    { Weapons.Artillery12PdrNapoleon, 3 },
                    { Weapons.Artillery3InchOrdnance, 3 },
                }
            },
            {
                Regiments.BatteryClark,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryCook,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryCooper,
                new()
                {
                    { Weapons.Artillery12PdrNapoleon, 2 },
                    { Weapons.Artillery3InchOrdnance, 2 },
                }
            },
            {
                Regiments.BatteryCrome,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryEdgell,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryGlassie,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryGraham,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.HeavyArtilleryGraham,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryHexamer,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryMatthews,
                new()
                {
                    { Weapons.Artillery12PdrNapoleon, 3 },
                    { Weapons.Artillery10PdrParrott, 3 }
                }
            },
            {
                Regiments.BatteryMcGilvery,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryOwen,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryPhillips,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryPotts,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryRansom,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryReynolds,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryRigby,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryStewart,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryThompson,
                new()
                {
                    { Weapons.Artillery12PdrNapoleon, 2 },
                    { Weapons.Artillery3InchOrdnance, 2 },
                }
            },
            {
                Regiments.BatteryTompkins,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryVonSehlen,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.BatteryWeaver,
                new()
                {
                    { Weapons.ArtilleryToolSpongeRammer, 100 }
                }
            },
            {
                Regiments.Brooklyn14th,
                new()
                {
                    { Weapons.PatternEnfield1853, 100 }
                }
            },
            {
                Regiments.Delaware1st,
                new()
                {
                    { Weapons.PatternEnfield1853, 100 }
                }
            },
            {
                Regiments.Illinois65th,
                new()
                {
                    { Weapons.SpringfieldM1861, 100 }
                }
            },
            {
                Regiments.Indiana14th,
                new()
                {
                    { Weapons.SpringfieldM1861, 100 }
                }
            },
            {
                Regiments.Indiana19th,
                new()
                {
                    { Weapons.SpringfieldM1861, 100 }
                }
            },
            {
                Regiments.Maine20th,
                new()
                {
                    { Weapons.PatternEnfield1853, 100 }
                }
            },
            {
                Regiments.Maine7th,
                new()
                {
                    { Weapons.PatternEnfield1853, 100 }
                }
            },
            {
                Regiments.MarylandPHB1st,
                new()
                {
                    { Weapons.SpringfieldM1855, 50 },
                    { Weapons.SpringfieldM1842, 50 }
                }
            },
            {
                Regiments.Maryland2nd,
                new()
                {
                    { Weapons.SpringfieldM1861, 100 }
                }
            },
            {
                Regiments.MarylandPHB3rd,
                new()
                {
                    { Weapons.SpringfieldM1855, 50 },
                    { Weapons.SpringfieldM1842, 50 }
                }
            },
            {
                Regiments.Massachusetts15th,
                new()
                {
                    { Weapons.LorenzM1854, 100 }
                }
            },
            {
                Regiments.Massachusetts28th,
                new()
                {
                    { Weapons.PatternEnfield1853, 100 }
                }
            },
            {
                Regiments.Michigan17th,
                new()
                {
                    { Weapons.SpringfieldM1855, 50 },
                    { Weapons.SpringfieldM1861, 50 }
                }
            },
            {
                Regiments.Michigan7th,
                new()
                {
                    { Weapons.SpringfieldM1855, 50 },
                    { Weapons.SpringfieldM1861, 50 }
                }
            },
            {
                Regiments.Minnesota1st,
                new()
                {
                    { Weapons.SpringfieldM1855, 70 },
                    { Weapons.SpringfieldM1861, 30 }
                }
            },
            {
                Regiments.NewYork126th,
                new()
                {
                    { Weapons.PatternEnfield1853, 100 }
                }
            },
            {
                Regiments.NewYorkMilitia12th,
                new()
                {
                    { Weapons.SpringfieldM1855, 50 },
                    { Weapons.SpringfieldM1842, 50 }
                }
            },
            {
                Regiments.NewYork20th,
                new()
                {
                    { Weapons.Mississippi1841, 100 }
                }
            },
            {
                Regiments.NewYork23rd,
                new()
                {
                    { Weapons.PatternEnfield1853, 100 }
                }
            },
            {
                Regiments.NewYork39th,
                new()
                {
                    { Weapons.SpringfieldM1842, 100 },
                    { Weapons.Mississippi1841, 100 }
                }
            },
            {
                Regiments.NewYork51st,
                new()
                {
                    { Weapons.SpringfieldM1861, 100 }
                }
            },
            {
                Regiments.NewYork52nd,
                new()
                {
                    { Weapons.PatternEnfield1853, 100 }
                }
            },
            {
                Regiments.NewYork5th,
                new()
                {
                    { Weapons.SpringfieldM1861, 100 },
                    { Weapons.SharpsRifle, 100 }
                }
            },
            {
                Regiments.NewYork69th,
                new()
                {
                    { Weapons.SpringfieldM1842, 100 }
                }
            },
            {
                Regiments.NewYork89th,
                new()
                {
                    { Weapons.PatternEnfield1853, 100 }
                }
            },
            {
                Regiments.NewYork9th,
                new()
                {
                    { Weapons.SpringfieldM1861, 100 }
                }
            },
            {
                Regiments.Ohio12th,
                new()
                {
                    { Weapons.LorenzM1854, 80 },
                    { Weapons.SpringfieldM1861, 20 }
                }
            },
            {
                Regiments.Ohio23rd,
                new()
                {
                    { Weapons.SpringfieldM1842, 30 },
                    { Weapons.LorenzM1854, 70 }
                }
            },
            {
                Regiments.Ohio30th,
                new()
                {
                    { Weapons.SpringfieldM1855, 50 },
                    { Weapons.SpringfieldM1861, 50 }
                }
            },
            {
                Regiments.Ohio32nd,
                new()
                {
                    { Weapons.LorenzM1854, 80 },
                    { Weapons.SpringfieldM1861, 20 }
                }
            },
            {
                Regiments.Ohio36th,
                new()
                {
                    { Weapons.LorenzM1854, 80 },
                    { Weapons.SpringfieldM1861, 20 }
                }
            },
            {
                Regiments.Ohio87th,
                new()
                {
                    { Weapons.SpringfieldM1855, 20 },
                    { Weapons.LorenzM1854, 80 }
                }
            },
            {
                Regiments.Ohio8th,
                new()
                {
                    { Weapons.SpringfieldM1855, 50 },
                    { Weapons.SpringfieldM1861, 50 }
                }
            },
            {
                Regiments.Pennsylvania114th,
                new()
                {
                    { Weapons.SpringfieldM1861, 100 }
                }
            },
            {
                Regiments.Pennsylvania28th,
                new()
                {
                    { Weapons.SpringfieldM1861, 100 }
                }
            },
            {
                Regiments.Pennsylvania32nd,
                new()
                {
                    { Weapons.SpringfieldM1842, 100 }
                }
            },
            {
                Regiments.Pennsylvania42nd,
                new()
                {
                    { Weapons.SharpsRifle, 100 }
                }
            },
            {
                Regiments.Pennsylvania4th,
                new()
                {
                    { Weapons.SharpsCarbine, 100 }
                }
            },
            {
                Regiments.Pennsylvania51st,
                new()
                {
                    { Weapons.SpringfieldM1861, 100 }
                }
            },
            {
                Regiments.Pennsylvania6th,
                new()
                {
                    { Weapons.SharpsCarbine, 100 }
                }
            },
            {
                Regiments.Pennsylvania72nd,
                new()
                {
                    { Weapons.SpringfieldM1861, 50 },
                    { Weapons.PatternEnfield1853, 50 }
                }
            },
            {
                Regiments.RhodeIsland4th,
                new()
                {
                    { Weapons.LorenzM1854, 50 },
                    { Weapons.SpringfieldM1861, 50 }
                }
            },
            {
                Regiments.USSharpshooters1st,
                new()
                {
                    { Weapons.SharpsRifle, 100 }
                }
            },
            {
                Regiments.USSharpshooters2nd,
                new()
                {
                    { Weapons.SharpsRifle, 100 }
                }
            },
            {
                Regiments.UnitedStates10th,
                new()
                {
                    { Weapons.SpringfieldM1861, 100 }
                }
            },
            {
                Regiments.UnitedStates2nd,
                new()
                {
                    { Weapons.SpringfieldM1861, 100 }
                }
            },
            {
                Regiments.Vermont9th,
                new()
                {
                    { Weapons.PatternEnfield1853, 100 }
                }
            },
            {
                Regiments.Wisconsin2nd,
                new()
                {
                    { Weapons.LorenzM1854, 70 },
                    { Weapons.SpringfieldM1861, 30 }
                }
            },
            {
                Regiments.Wisconsin6th,
                new()
                {
                    { Weapons.LorenzM1854, 70 },
                    { Weapons.SpringfieldM1861, 30 }
                }
            }
        };
    }
}