using System.Collections.Generic;

namespace WarOfRightsWeb.Constants
{
    // NOTE: Generated by WarOfRightsTools from text_ui_items.xml

    public static class Weapons
    {
        // NOTE: Generated item identifiers 
        // TODO: Refactor constant names
        public const string BuckAndBall = "BuckAndBall";
        public const string BuckShot = "BuckShot";
        public const string CompressionBall = "CompressionBall";
        public const string HexagonalBullet = "HexagonalBullet";
        public const string MinieBall = "MinieBall";
        public const string PistolBall = "PistolBall";
        public const string RoundBall = "RoundBall";
        public const string SpringfieldM1861 = "SpringfieldM1861";
        public const string SpringfieldM1855 = "SpringfieldM1855";
        public const string SpringfieldM1842 = "SpringfieldM1842";
        public const string LorenzM1854 = "LorenzM1854";
        public const string Mississippi1841 = "Mississippi1841";
        public const string PatternEnfield1853 = "PatternEnfield1853";
        public const string SharpsRifle = "SharpsRifle";
        public const string SharpsCarbine = "SharpsCarbine";
        public const string Whitworth = "Whitworth";
        public const string ColtNavyM1851 = "ColtNavyM1851";
        public const string ColtPocketM1849 = "ColtPocketM1849";
        public const string ColtWalkerM1847 = "ColtWalkerM1847";
        public const string ColtArmyM1860 = "ColtArmyM1860";
        public const string LeMat = "LeMat";
        public const string RemingtonM1858 = "RemingtonM1858";
        public const string USFtOfficerSword1850 = "USFtOfficerSword1850";
        public const string USLightCavalrySaber1860 = "USLightCavalrySaber1860";
        public const string USNCOSword1840 = "USNCOSword1840";
        public const string Bayonet = "Bayonet";
        public const string SwordBayonet = "SwordBayonet";
        public const string FootArtillerySwordUS = "FootArtillerySwordUS";
        public const string FootArtillerySwordCS = "FootArtillerySwordCS";
        public const string ArtilleryToolSpongeRammer = "ArtilleryToolSpongeRammer";

        // Artillery
        public const string Artillery10PdrParrott = "Artillery10PdrParrott";
        public const string Artillery12PdrNapoleon = "Artillery12PdrNapoleon";
        public const string Artillery3InchOrdnance = "Artillery3InchOrdnance";

        // ui_(?<id>\w+)_title
        // NOTE: Generated item display names        
        public static Dictionary<string, string> DisplayNames = new()
        {
            { BuckAndBall, "Buck And Ball" },
            { BuckShot, "Buck Shot" },
            { CompressionBall, "Compression Ball" },
            { HexagonalBullet, "Hexagonal Bullet" },
            { MinieBall, "Minie Ball" },
            { PistolBall, "Pistol Ball" },
            { RoundBall, "Round Ball" },
            { SpringfieldM1861, "Springfield M1861" },
            { SpringfieldM1855, "Springfield M1855" },
            { SpringfieldM1842, "Springfield M1842" },
            { LorenzM1854, "Lorenz M1854" },
            { Mississippi1841, "Mississippi M1841" },
            { PatternEnfield1853, "Pattern Enfield M1853" },
            { SharpsRifle, "Sharps Infantry Rifle M1859" },
            { SharpsCarbine, "Sharps Carbine M1859" },
            { Whitworth, "Whitworth Rifle M1854" },
            { ColtNavyM1851, "Colt Navy M1851" },
            { ColtPocketM1849, "Colt Pocket M1849" },
            { ColtWalkerM1847, "Colt Walker M1847" },
            { ColtArmyM1860, "Colt Army M1860" },
            { LeMat, "LeMat M1855" },
            { RemingtonM1858, "Remington New Army Revolver M1858" },
            { USFtOfficerSword1850, "US Foot Officer Sword M1850" },
            { USLightCavalrySaber1860, "US Light Cavalry Saber M1860" },
            { USNCOSword1840, "US NCO Sword M1840" },
            { Bayonet, "Socket Bayonet" },
            { SwordBayonet, "Sword Bayonet" },
            { FootArtillerySwordUS, "Foot Artillery Sword US" },
            { FootArtillerySwordCS, "Foot Artillery Sword CS" },
            { ArtilleryToolSpongeRammer, "Sponge Rammer" },

            { Artillery10PdrParrott, "10-pounder Parrott" },
            { Artillery12PdrNapoleon, "12-pounder Napoleon" },
            { Artillery3InchOrdnance, "3-inch ordnance" },
        };

        // ui_{id}_info\d
        // NOTE: Generated item parameters (prepared for html)        
        public static Dictionary<string, string> Parameters = new()
        {
            { BuckAndBall, "" },
            { BuckShot, "" },
            { CompressionBall, "" },
            { HexagonalBullet, "" },
            { MinieBall, "" },
            { PistolBall, "" },
            { RoundBall, "" },
            { SpringfieldM1861, "Type: Rifled Musket<br>Caliber: .58\"<br>ROF: 3 RPM<br>Length: 56\"<br>Weight: 9 lbs<br>Range: 500 yds<br>" },
            { SpringfieldM1855, "Type: Rifled Musket<br>Caliber: .58\"<br>ROF: 3 RPM<br>Length: 56\"<br>Weight: 9 lbs<br>Range: 500 yds<br>" },
            { SpringfieldM1842, "Type: Smoothbore<br>Caliber: .69\"<br>ROF: 3 RPM<br>Length: 58\"<br>Weight: 10 lbs<br>Range: 100 yds<br>" },
            { LorenzM1854, "Type: Rifled Musket<br>Caliber: .54\"<br>ROF: 3 RPM<br>Length: 37.52\"<br>Weight: 8.82 lbs<br>Range: 300 yds<br>" },
            { Mississippi1841, "Type: Rifled Musket<br>Caliber: .58\"<br>ROF: 3 RPM<br>Length: 48.5\"<br>Weight: 9.25 lbs<br>Range: 1.100 yds<br>" },
            { PatternEnfield1853, "Type: Rifled Musket<br>Caliber: .577\"<br>ROF: 3 RPM<br>Length: 55\"<br>Weight: 9.5 lbs<br>Range: 1000 yds<br>" },
            { SharpsRifle, "Type: Rifled Musket<br>Caliber: .52\"<br>ROF: 7 RPM<br>Length: 47\"<br>Weight: 9.5 lbs<br>Range: 500 yds<br>" },
            { SharpsCarbine, "Type: Rifled Musket<br>Caliber: .54\"<br>ROF: 7 RPM<br>Length: 39.19\"<br>Weight: 8.37 lbs<br>Range: 500 yds<br>" },
            { Whitworth, "Type: Rifled Musket<br>Caliber: .54\"<br>ROF: 3 RPM<br>Length: 49\"<br>Weight: 9 lbs<br>Range: 1000 yds<br>" },
            { ColtNavyM1851, "Type: Revolver<br>Caliber: .36\"<br>ROF: 6 RPM<br>Length: 14\"<br>Weight: 2.7 lbs<br>Range: 75 yds<br>" },
            { ColtPocketM1849, "Type: Revolver<br>Caliber: .44\"<br>ROF: 6 RPM<br>Length: 14\"<br>Weight: 2.7 lbs<br>Range: 75 yds<br>" },
            { ColtWalkerM1847, "Type: Revolver<br>Caliber: .58\"<br>ROF: 6 RPM<br>Length: 16\"<br>Weight: 3.5 lbs<br>Range: 75 yds<br>" },
            { ColtArmyM1860, "Type: Revolver<br>Caliber: .44\"<br>ROF: 6 RPM<br>Length: 14\"<br>Weight: 2.7 lbs<br>Range: 75 yds<br>" },
            { LeMat, "Type: Revolver<br>Caliber: .42\"<br>ROF: 9 RPM<br>Length: 13.25\"<br>Weight: 3.1 lbs<br>Range: 40 yds<br>" },
            { RemingtonM1858, "Type: Revolver<br>Caliber: .44\"<br>ROF: 6 RPM<br>Length: 13.25\"<br>Weight: 2.8 lbs<br>Range: 75 yds<br>" },
            { USFtOfficerSword1850, "Type: Sword<br>Blade Length: 15.5\"<br>Weight: 4.5 lbs<br>" },
            { USLightCavalrySaber1860, "Type: Saber<br>Length: 35\"<br>Weight: 2.25 lbs<br>" },
            { USNCOSword1840, "Type: Sword<br>Length: 15.5\"<br>Weight: 1 lbs 14 oz<br>" },
            { Bayonet, "Type: Bayonet<br>Length: 18\"<br>Weight: 1.75 lbs<br>" },
            { SwordBayonet, "Type: Bayonet<br>Length: 21.6\"<br>Weight: 2.85 lbs<br>" },
            { FootArtillerySwordUS, "Type: Sword<br>Blade Length: 15.5\"<br>Weight: 4.5 lbs<br>" },
            { FootArtillerySwordCS, "Type: Sword<br>Blade Length: 15.5\"<br>Weight: 4.5 lbs<br>" },
            { ArtilleryToolSpongeRammer, "Type: Artillery Tool<br>Length: 50.6\"<br>Weight: 3.85 lbs<br>" },

            { Artillery10PdrParrott, "Type: Artillery<br>Length: 50.6\"<br>Weight: 3.85 lbs<br>" },
            { Artillery12PdrNapoleon, "12-pounder Napoleon" },
            { Artillery3InchOrdnance, "3-inch ordnance" },

        };

        // ui_{id}_description
        // NOTE: Generated item descriptions (raw)        
        public static Dictionary<string, string> Descriptions = new()
        {
            { BuckAndBall, "" },
            { BuckShot, "" },
            { CompressionBall, "" },
            { HexagonalBullet, "" },
            { MinieBall, "" },
            { PistolBall, "" },
            { RoundBall, "" },
            { SpringfieldM1861, "The Springfield M1861 was one of the most common rifles during the war. This weapon was extensively used by the infantry of both sides, and was the third weapon produced by the US with mass-produced rifling." },
            { SpringfieldM1855, "The Model 1855 was an experiment of the US Army to use the Maynard tape priming system, though its poor testing in the field meant that they reverted to the conventional brass caps instead. However, the 1855 was also inovative for being the first rifled-musket to be issued to regular troops in the US. " },
            { SpringfieldM1842, "A hallmark of older styles of musketry, the M1842 Springfield was widely used during the Mexican-American War as much as in the Civil War twenty years later. With a large .69 caliber barrel, the 1842 could do some serious damage to an opponent, though it lacked for accuracy due to being a smoothbore weapon. However, the barrel was designed extra thick to accomodate for later rifling once the technology became available." },
            { LorenzM1854, "The Lorenz M1854 Rifle, an Austrian make. 392.000 were imported by the Union, 100.000 for the Confederacy. Union versions tended to get rebored to be .58 caliber so that the same ammo could be used, however the Confederates did not have the machinery to do such re-boring, so Confederate versions tended to stay at .54 caliber." },
            { Mississippi1841, "The Mississippi M1841 was originally produced by the Harper's Ferry Armory, and first used by its namesake, the militiamen of Mississippi that fought under Andrew Jackson at New Orleans. Most used by Confederate Infantry, Sergeants and some Corporals, it was also a popular choice by Confederate Cavalry and Sharpshooters." },
            { PatternEnfield1853, "The Pattern Enfield M1853 Rifled Muskets had been imported From Great Britain in numbers up to 900.000 and were being used extensively by both sides, mostly because it could fire the same bullet as the Springfield M1861 which helped keep costs low. Their barrels were often blued by the Royal Armory to help prevent the rust buildup often seen on the American &quot;Rustfields.&quot;" },
            { SharpsRifle, "The Sharps Infantry Rifle M1859 differs from contemporary muzzleloaders by being loaded directly from the breach. This allows for much faster reloading as the soldier doesnt need to spend time ramming down the cartridge. The Confederates copied this weapon to make something called the Robinson Carbine. Both looked the same, though with a tad different markings." },
            { SharpsCarbine, "The Sharps Carbine M1859 is a shorter version of the Sharps Infantry Rifle M1859, making it very useful for cavalry. It has the same breach loading mechanism as the Sharps Infantry Rifle. The Sharps became one of the most iconic and popular weapons used by cavalry troops during and after the Civil War to great effect." },
            { Whitworth, "The Whitworth was originally designed by Sir Joseph Whitworth, and was one of the first examples of a &quot;sniper rifle&quot; once mounted with a scope. They were highly prized weapons by Sharpshooters on both sides during the time of the Civil War, and two Union generals are said to have lost their lives due to this very accurate weapon." },
            { ColtNavyM1851, "Colt produced several designs for use by the US military, including a design specifically tailored for the Navy, sporting a lower .36 caliber in comparison to its larger .44 caliber brothers. The 1851 was also very popular for civilian sale as well, which the enterprising Colt was quick to capitalize on. " },
            { ColtPocketM1849, "With the introduction of further designs by Colt and the many competitors that sprang up after him, some delineation had to be made between revolvers. Most were known as &quot;saddle guns,&quot; since they were too heavy to be worn normally. Colt introduced the 1849 &quot;Pocket&quot; Colt as one that could be comfortably worn on one's person. Despite its smaller size it still was a mean weapon to face in combat, being a .44 caliber weapon." },
            { ColtWalkerM1847, "Also known as the &quot;horse killer,&quot; the Walker revolver was a fiercesome weapon first designed by Colt to be used by the Texas Rangers after the success of his maiden design, the Patterson. It was loaded with the same amount of powder used in muskets, and was often carried by heavy cavalry to take out enemy horses, and was often placed in holsters on the pommel of a saddle. The design was later improved by Colt with the 1848 Dragoon model." },
            { ColtArmyM1860, "One of the most iconic weapons produced by the Colt Manufacturing Co., the M1860 Colt was used by officers and cavalrymen of both sides during the Civil War. When the war first broke, Samuel Colt was quick to have the government contract his revolvers exclusively, though many of his revolvers &quot;managed&quot; to reach Confederate hands as well." },
            { LeMat, "Originally developed just prior to the war by Jean Alexander LeMatt, a close cousin of future general Pierre Beauregard. Beauregard was wearing one that was gifted to him by his cousin as he ordered his troops to begin bombardment of Fort Sumter. Once the Union took control of New Orleans, LeMatt fled to Paris to continue production in France, while his nine-shot revolver with its underslung sixteen-gauge shotgun barrel became highly popular among Confederate officers." },
            { RemingtonM1858, "Remington quickly became the largest competitor of Colt in the weapons manufacturing market, and the enterprising upper-strap design on the M1858 is one example of their fierce rivalry. While many soldiers were issued Colts, many preferred the ease of reloading and the durability offered by the design of the 1858." },
            { USFtOfficerSword1850, "Fashioned after many European military blades, the Foot Officer's Sword was intended to be worn by company level officers of Infantry and Artillery of the rank of Major and below. It was accompanied in implementation by it's sister blade, the Staff Officer's Sword, which had a different design to it's brass guard." },
            { USLightCavalrySaber1860, "Made as a lighter replacement of the cumbersome M1840 &quot;Wristbreaker&quot; Heavy Cavalry Saber, the Light Cavalry Saber was put into production at the same time that the United States was reformulating its cavalry to better match military developments on the European continent. Both the north and south made large use of this model of blade." },
            { USNCOSword1840, "Based largely off of French épées, or small swords, the 1840 NCO sword was a symbol of a non-commissioned officer's authority in a regiment. In practice, many sergeants and corporals, though authorized to carry it, put more stock in a musket and bayonet. However, such weapons added dash and daring to those on parade!  " },
            { Bayonet, "The socket bayonet was an important step forward in comparison to earlier &quot;plug&quot; style bayonets, which were inserted directly in the barrel of the musket being used and prevented it from being fired. By 1700, the socket bayonet was widely adopted, while fifteen years later the triangular-shaped blade was also introduced. Soldiers in the Civil War prefered not to get close with weapons they considered barbarous, instead retreating in the face of glinting steel. " },
            { SwordBayonet, "The 19th century saw the introduction of the sword bayonet, with the 1855 sword bayonet being the first used by the US for their purposes. While originally designed as a variant bayonet for use on the 1855 Springfield Musket, many more were made for the earlier 1841 Mississippi rifle. Its design also allowed it to be used as a small sword in its own right when not attached to a rifle." },
            { FootArtillerySwordUS, "A nice description for a foot artillery sword" },
            { FootArtillerySwordCS, "A nice description for a foot artillery sword" },
            { ArtilleryToolSpongeRammer, "Used for cleaning out the embers of the previous shot on the artillery and for ramming the new shell down the barrel." },
        };
    }
}
