using System.Collections.Generic;

namespace WarOfRightsWeb.Constants
{
    // NOTE: Generated by WarOfRightsTools from text_ui_items.xml

    public static class Weapons
    {
        // NOTE: Database weapon identifiers
        public const string BuckAndBall = "BuckAndBall";
        public const string BuckShot = "BuckShot";
        public const string CompressionBall = "CompressionBall";
        public const string HexagonalBullet = "HexagonalBullet";
        public const string MinieBall = "MinieBall";
        public const string PistolBall = "PistolBall";
        public const string RoundBall = "RoundBall";
        public const string SpringfieldM1861 = "SpringfieldM1861";
        public const string SpringfieldM1855 = "SpringfieldM1855";
        public const string SpringfieldM1842 = "SpringfieldM1842";
        public const string LorenzM1854 = "LorenzM1854";
        public const string Mississippi1841 = "Mississippi1841";
        public const string PatternEnfield1853 = "PatternEnfield1853";
        public const string SharpsRifle = "SharpsRifle";
        public const string SharpsCarbine = "SharpsCarbine";
        public const string Whitworth = "Whitworth";
        public const string ColtNavyM1851 = "ColtNavyM1851";
        public const string ColtPocketM1849 = "ColtPocketM1849";
        public const string ColtWalkerM1847 = "ColtWalkerM1847";
        public const string ColtArmyM1860 = "ColtArmyM1860";
        public const string LeMat = "LeMat";
        public const string RemingtonM1858 = "RemingtonM1858";
        public const string USFtOfficerSword1850 = "USFtOfficerSword1850";
        public const string USLightCavalrySaber1860 = "USLightCavalrySaber1860";
        public const string USNCOSword1840 = "USNCOSword1840";
        public const string Bayonet = "Bayonet";
        public const string SwordBayonet = "SwordBayonet";
        public const string FootArtillerySwordUS = "FootArtillerySwordUS";
        public const string FootArtillerySwordCS = "FootArtillerySwordCS";
        public const string ArtilleryToolSpongeRammer = "ArtilleryToolSpongeRammer";

        // Missing weapons ...
        public const string Artillery10PdrParrott = "Artillery10PdrParrott";
        public const string Artillery12PdrNapoleon = "Artillery12PdrNapoleon";
        public const string Artillery3InchOrdnance = "Artillery3InchOrdnance";

        public static string[] Swords = {USFtOfficerSword1850, USLightCavalrySaber1860, USNCOSword1840};
        public static string[] Revolvers = { RemingtonM1858, LeMat, ColtWalkerM1847, ColtPocketM1849, ColtNavyM1851, ColtArmyM1860 };
        public static string[] Rifles = { LorenzM1854, Mississippi1841, PatternEnfield1853, SharpsCarbine, SharpsRifle, SpringfieldM1861, SpringfieldM1842, SpringfieldM1855, Whitworth };
        public static string[] Artillery = { Artillery3InchOrdnance, Artillery12PdrNapoleon, Artillery10PdrParrott };
        public static string[] Misc = { Bayonet, SwordBayonet, ArtilleryToolSpongeRammer };
    }
}
