name: .NET

on:
  push:
    tags:
      - v.*

jobs:
  publish:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish /p:PublishProfile=Properties/PublishProfiles/FolderProfile.pubxml
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: panayot
        server: 91.230.195.120
        port: 22
        local_path: ./publish/*
        remote_path: /var/www/1usssf.eu
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
